apiVersion: skaffold/v1beta16
kind: Config
build:
  artifacts:
    - image: petclinic
      docker:
        dockerfile: Dockerfile-app
    - image: petclinic-db
      docker:
        dockerfile: Dockerfile-db
  local:
    push: true
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
