apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
  serviceName: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: petclinic
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http-server
#        resources:
#          limits:
#            cpu: 100m
#            memory: 128Mi
#          requests:
#            cpu: 100m
#            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: petclinic
